### ISSUE TITLE
Food selector 

### ISSUE THREAD

**Issue by Naemeia** [Gwenillia/Better-Equideow#75]
Hi ! While taking care of my horses with the extension, I noticed that the food selector was kinda buggy. With foals, it won't select anything to eat and sometimes with horses it will only select the oat ! 
Have a nice day !

**Comment by Gwenillia** [comment]
Oh no 🥺 with the latest version ? That is a problem of being alone to both dev and test ahah I will dig this to make a fix. 

Thanks a lot for the info 🙏🏻

**Comment by Naemeia** [comment]
(j'ai vu que tu es française haha en fait) Mais oui du coup le problème semble en effet être apparu avec la dernière version ! Merci beaucoup pour le temps que tu prends à améliorer l'extension !

**Comment by Gwenillia** [comment]
Ahah oui, J'ai pas eu le temps la de m'en occuper, je m'en occuperai au plus tard pour ce weekend. Je le note ^^ Merci encore pour le retour

**Comment by Gwenillia** [comment]
**Task** 
- [ ] Repair Food Selector. 

**Background:** 
Since the last 2.2.0 update. The Food Selector seems not to be working properly. 
Not selecting anything with foals and sometimes not selecting hay as expected

**AC:**
- [ ] Food selector working properly with foals
- [ ] Food selector working properly with horses 
- [ ] Make sure there is no regression with the messageBox

**Comment by Gwenillia** [comment]
@Naemeia Je publie la mise a jour, elle devrait arriver rapidement dependemment de la rapidité de google 😂 

Issue closed and solved in #76 
being published on google chrome
